// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "school_schedule_2/internal/domain/dto"
	enums "school_schedule_2/internal/domain/model/enums"

	mock "github.com/stretchr/testify/mock"

	model "school_schedule_2/internal/domain/model"
)

// LessonRepo is an autogenerated mock type for the lessonRepo type
type LessonRepo struct {
	mock.Mock
}

type LessonRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *LessonRepo) EXPECT() *LessonRepo_Expecter {
	return &LessonRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: lesson
func (_m *LessonRepo) Create(lesson *model.Lesson) (*model.Lesson, error) {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Lesson) (*model.Lesson, error)); ok {
		return rf(lesson)
	}
	if rf, ok := ret.Get(0).(func(*model.Lesson) *model.Lesson); ok {
		r0 = rf(lesson)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Lesson) error); ok {
		r1 = rf(lesson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LessonRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LessonRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - lesson *model.Lesson
func (_e *LessonRepo_Expecter) Create(lesson interface{}) *LessonRepo_Create_Call {
	return &LessonRepo_Create_Call{Call: _e.mock.On("Create", lesson)}
}

func (_c *LessonRepo_Create_Call) Run(run func(lesson *model.Lesson)) *LessonRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Lesson))
	})
	return _c
}

func (_c *LessonRepo_Create_Call) Return(_a0 *model.Lesson, _a1 error) *LessonRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LessonRepo_Create_Call) RunAndReturn(run func(*model.Lesson) (*model.Lesson, error)) *LessonRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *LessonRepo) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LessonRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LessonRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *LessonRepo_Expecter) Delete(id interface{}) *LessonRepo_Delete_Call {
	return &LessonRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *LessonRepo_Delete_Call) Run(run func(id int64)) *LessonRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *LessonRepo_Delete_Call) Return(_a0 error) *LessonRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LessonRepo_Delete_Call) RunAndReturn(run func(int64) error) *LessonRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: req
func (_m *LessonRepo) FindAll(req dto.FindAllLessonFilter) ([]*model.Lesson, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.FindAllLessonFilter) ([]*model.Lesson, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.FindAllLessonFilter) []*model.Lesson); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.FindAllLessonFilter) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LessonRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type LessonRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - req dto.FindAllLessonFilter
func (_e *LessonRepo_Expecter) FindAll(req interface{}) *LessonRepo_FindAll_Call {
	return &LessonRepo_FindAll_Call{Call: _e.mock.On("FindAll", req)}
}

func (_c *LessonRepo_FindAll_Call) Run(run func(req dto.FindAllLessonFilter)) *LessonRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.FindAllLessonFilter))
	})
	return _c
}

func (_c *LessonRepo_FindAll_Call) Return(_a0 []*model.Lesson, _a1 error) *LessonRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LessonRepo_FindAll_Call) RunAndReturn(run func(dto.FindAllLessonFilter) ([]*model.Lesson, error)) *LessonRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *LessonRepo) GetByID(id int64) (*model.Lesson, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.Lesson, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Lesson); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LessonRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LessonRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *LessonRepo_Expecter) GetByID(id interface{}) *LessonRepo_GetByID_Call {
	return &LessonRepo_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *LessonRepo_GetByID_Call) Run(run func(id int64)) *LessonRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *LessonRepo_GetByID_Call) Return(_a0 *model.Lesson, _a1 error) *LessonRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LessonRepo_GetByID_Call) RunAndReturn(run func(int64) (*model.Lesson, error)) *LessonRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// LessonExists provides a mock function with given fields: name, slot
func (_m *LessonRepo) LessonExists(name enums.OfficeName, slot enums.TimeSlotName) bool {
	ret := _m.Called(name, slot)

	if len(ret) == 0 {
		panic("no return value specified for LessonExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(enums.OfficeName, enums.TimeSlotName) bool); ok {
		r0 = rf(name, slot)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LessonRepo_LessonExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LessonExists'
type LessonRepo_LessonExists_Call struct {
	*mock.Call
}

// LessonExists is a helper method to define mock.On call
//   - name enums.OfficeName
//   - slot enums.TimeSlotName
func (_e *LessonRepo_Expecter) LessonExists(name interface{}, slot interface{}) *LessonRepo_LessonExists_Call {
	return &LessonRepo_LessonExists_Call{Call: _e.mock.On("LessonExists", name, slot)}
}

func (_c *LessonRepo_LessonExists_Call) Run(run func(name enums.OfficeName, slot enums.TimeSlotName)) *LessonRepo_LessonExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(enums.OfficeName), args[1].(enums.TimeSlotName))
	})
	return _c
}

func (_c *LessonRepo_LessonExists_Call) Return(_a0 bool) *LessonRepo_LessonExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LessonRepo_LessonExists_Call) RunAndReturn(run func(enums.OfficeName, enums.TimeSlotName) bool) *LessonRepo_LessonExists_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: lesson
func (_m *LessonRepo) Update(lesson *model.Lesson) (*model.Lesson, error) {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Lesson) (*model.Lesson, error)); ok {
		return rf(lesson)
	}
	if rf, ok := ret.Get(0).(func(*model.Lesson) *model.Lesson); ok {
		r0 = rf(lesson)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Lesson) error); ok {
		r1 = rf(lesson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LessonRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LessonRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - lesson *model.Lesson
func (_e *LessonRepo_Expecter) Update(lesson interface{}) *LessonRepo_Update_Call {
	return &LessonRepo_Update_Call{Call: _e.mock.On("Update", lesson)}
}

func (_c *LessonRepo_Update_Call) Run(run func(lesson *model.Lesson)) *LessonRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Lesson))
	})
	return _c
}

func (_c *LessonRepo_Update_Call) Return(_a0 *model.Lesson, _a1 error) *LessonRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LessonRepo_Update_Call) RunAndReturn(run func(*model.Lesson) (*model.Lesson, error)) *LessonRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewLessonRepo creates a new instance of LessonRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonRepo {
	mock := &LessonRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
