// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "school_schedule_2/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	model "school_schedule_2/internal/domain/model"
)

// ClassRepo is an autogenerated mock type for the classRepo type
type ClassRepo struct {
	mock.Mock
}

type ClassRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ClassRepo) EXPECT() *ClassRepo_Expecter {
	return &ClassRepo_Expecter{mock: &_m.Mock}
}

// CreateClass provides a mock function with given fields: class
func (_m *ClassRepo) CreateClass(class *model.Class) (*model.Class, error) {
	ret := _m.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for CreateClass")
	}

	var r0 *model.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Class) (*model.Class, error)); ok {
		return rf(class)
	}
	if rf, ok := ret.Get(0).(func(*model.Class) *model.Class); ok {
		r0 = rf(class)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Class) error); ok {
		r1 = rf(class)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassRepo_CreateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClass'
type ClassRepo_CreateClass_Call struct {
	*mock.Call
}

// CreateClass is a helper method to define mock.On call
//   - class *model.Class
func (_e *ClassRepo_Expecter) CreateClass(class interface{}) *ClassRepo_CreateClass_Call {
	return &ClassRepo_CreateClass_Call{Call: _e.mock.On("CreateClass", class)}
}

func (_c *ClassRepo_CreateClass_Call) Run(run func(class *model.Class)) *ClassRepo_CreateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Class))
	})
	return _c
}

func (_c *ClassRepo_CreateClass_Call) Return(_a0 *model.Class, _a1 error) *ClassRepo_CreateClass_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassRepo_CreateClass_Call) RunAndReturn(run func(*model.Class) (*model.Class, error)) *ClassRepo_CreateClass_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: req
func (_m *ClassRepo) FindAll(req dto.FindAllClassesFilter) ([]*model.Class, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.FindAllClassesFilter) ([]*model.Class, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.FindAllClassesFilter) []*model.Class); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.FindAllClassesFilter) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type ClassRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - req dto.FindAllClassesFilter
func (_e *ClassRepo_Expecter) FindAll(req interface{}) *ClassRepo_FindAll_Call {
	return &ClassRepo_FindAll_Call{Call: _e.mock.On("FindAll", req)}
}

func (_c *ClassRepo_FindAll_Call) Run(run func(req dto.FindAllClassesFilter)) *ClassRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.FindAllClassesFilter))
	})
	return _c
}

func (_c *ClassRepo_FindAll_Call) Return(_a0 []*model.Class, _a1 error) *ClassRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassRepo_FindAll_Call) RunAndReturn(run func(dto.FindAllClassesFilter) ([]*model.Class, error)) *ClassRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *ClassRepo) GetByID(id int64) (*model.Class, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.Class, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Class); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ClassRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *ClassRepo_Expecter) GetByID(id interface{}) *ClassRepo_GetByID_Call {
	return &ClassRepo_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *ClassRepo_GetByID_Call) Run(run func(id int64)) *ClassRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *ClassRepo_GetByID_Call) Return(_a0 *model.Class, _a1 error) *ClassRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassRepo_GetByID_Call) RunAndReturn(run func(int64) (*model.Class, error)) *ClassRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClass provides a mock function with given fields: filter
func (_m *ClassRepo) UpdateClass(filter dto.UpdateClassFilter) (*model.Class, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClass")
	}

	var r0 *model.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.UpdateClassFilter) (*model.Class, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.UpdateClassFilter) *model.Class); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.UpdateClassFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassRepo_UpdateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClass'
type ClassRepo_UpdateClass_Call struct {
	*mock.Call
}

// UpdateClass is a helper method to define mock.On call
//   - filter dto.UpdateClassFilter
func (_e *ClassRepo_Expecter) UpdateClass(filter interface{}) *ClassRepo_UpdateClass_Call {
	return &ClassRepo_UpdateClass_Call{Call: _e.mock.On("UpdateClass", filter)}
}

func (_c *ClassRepo_UpdateClass_Call) Run(run func(filter dto.UpdateClassFilter)) *ClassRepo_UpdateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.UpdateClassFilter))
	})
	return _c
}

func (_c *ClassRepo_UpdateClass_Call) Return(_a0 *model.Class, _a1 error) *ClassRepo_UpdateClass_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassRepo_UpdateClass_Call) RunAndReturn(run func(dto.UpdateClassFilter) (*model.Class, error)) *ClassRepo_UpdateClass_Call {
	_c.Call.Return(run)
	return _c
}

// NewClassRepo creates a new instance of ClassRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassRepo {
	mock := &ClassRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
